cws-status: Investigate out of bounds error
Sometimes I was getting the following exception which caused the program
to fail:

    $ cws-status 'AODocs - Universal'
    Traceback (most recent call last):
      File ".../cws-status/cws-status", line 117, in <module>
        matched_extensions.append((name, item_statuses[i]))
    IndexError: list index out of range

Add a couple of print statements to see what's going on.